// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject
package main

import (
	"go-learn/chapter04/configs"
	"go-learn/chapter04/dao"
	internal_dao "go-learn/chapter04/internal/dao"
)

func InitDao(ip string, port int) *dao.Dao {
	NewConf := configs.NewConf(ip, port)
	FakeRedis := internal_dao.MakeFakeRedis(NewConf)

	return FakeRedis
}
